budgeter/urls.py
from django.urls import path
from .views import (
    TransactionDeleteView,
    TransactionListListView
    )
from . import views

urlpatterns = [
    path('', views.home, name='budgeter-home'),
    path('create/', views.create, name='budgeter-create'),
    path('dashboard/<int:id>', views.dashboard, name='budgeter-dashboard'),
    path('dashboard/my_budgets', TransactionListListView.as_view(), name='transactionlist-lists'),
    path('dashboard/transaction/<int:pk>/delete/', TransactionDeleteView.as_view(), name='transaction-delete')
]

financial_planner/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register-page'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login-page'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout-page'),
    path('', include('budgeter.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

budgeter/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone, dateformat


class TransactionList(models.Model):
    """List of transactions that is unique to each User so
    that they can manage and see their own transactions.

    Attributes
    ----------
    user: :class:`ForeignKey`
        User who created the transaction list. If the User has
        been deleted, then all of the transaction lists that were
        made by the User will be deleted.
    name: :class:`CharField`
        Name of the TransactionList.
    starting_balance: :class:`DecimalField`
        The starting balance (initial transaction) of the transaction
        list. This value is set by the User.
    """

    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name="transactionlist",
                             null=True)
    name = models.CharField(max_length=150)
    starting_balance = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return f"User: {self.user}\n" \
               f"Name: {self.name}"


class Transaction(models.Model):
    """Transactions that Users can create in their
    TransactionList.

    Attributes
    ----------
    t_list: :class:`ForeignKey`
        Every Transaction belongs to a TransactionList.
        Every TransactionList is unique to a User. This
        allows for Users to have multiple TransactionLists,
        each with different Transactions.
    date_posted: :class:`DateField`
        When the Transaction was made by the User. The
        default is the current date, but may be set
        by the User.
    payee: :class:`CharField`
        Payee of the Transaction. The User sets who the
        payee of the Transaction was.
    memo: :class:`TextField`
        Any notes that the User would like to leave for
        the Transaction.
    ingoing: :class:`DecimalField`
        The ingoing dollar value of the Transaction. Set to
        two decimal places for currency format.
    outgoing: :class:`DecimalField`
        The outgoing dollar value of the Transaction. Set
        to two decimal places for the currency format.
    """

    t_list = models.ForeignKey(TransactionList,
                               on_delete=models.CASCADE,
                               related_name='transaction',
                               null=True)
    date_posted = models.DateField(blank=False,
                                   default=dateformat.format(timezone.now(), 'm/d/y'))
    payee = models.CharField(max_length=100)
    memo = models.CharField(blank=True, max_length=300)
    ingoing = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    outgoing = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return f"User: {self.t_list.user}\n" \
               f"Budget: {self.t_list.name}\n" \
               f"Payee: {self.payee}\n" \
               f"Ingoing: ${self.ingoing}\n" \
               f"Outgoing: ${self.outgoing}"

budgeter/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Transaction, TransactionList


class CreateNewList(forms.ModelForm):
    """Form for the User to create a new TransactionList.
    """

    class Meta:
        model = TransactionList
        fields = ('name',
                  'starting_balance'
                  )

        labels = {
            'name': _('Name of Budget'),
            'starting_balance': _('Starting Balance')
        }


class CreateNewTransaction(forms.ModelForm):
    """Form for the User to create a new Transaction.
    Features a Date-picker for the date_posted field.
    """

    class Meta:
        model = Transaction
        fields = ('date_posted',
                  'payee',
                  'memo',
                  'ingoing',
                  'outgoing'
                  )

        labels = {
            'date_posted': _('Date of Transaction'),
            'payee': _('Payee'),
            'memo': _('Memo'),
            'ingoing': _('Ingoing'),
            'outgoing': _('Outgoing')
        }

        widgets = {
            'date_posted': forms.DateTimeInput(attrs={'class': 'datepicker'})
        }

budgeter/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Sum
from django.utils import timezone
from django.views.generic import DeleteView, ListView
from .models import TransactionList, Transaction
from .forms import CreateNewList, CreateNewTransaction


def home(request):
    """If the User is already logged in, then Home-view will
    redirect the user to either:
        their dashboard if they have already created a budget.
        the Budgeter-create page to create their first budget.

    Otherwise, the Home-view will render the home.html template.
    """

    if request.user.is_authenticated:
        t_list = request.user.transactionlist.first()
        if t_list:
            return redirect("/dashboard/%i" % t_list.id + "?id=%i" % t_list.id)
        else:
            return redirect("budgeter-create")

    return render(request, 'budgeter/home.html')


def create(request):
    """Requires the User to be logged-in to access Create-view.
    Renders a form for the User to create a new budget and saves
    their starting balance as the initial transaction in the new
    budget.

    If the User is not logged-in, then the view renders a custom 404
    Error page.

    Variables passed through to the template:
        title: :class:`String`
            Title of the view.
        form: :class:`form`
            Rendered TransactionList form for the User.
    """

    if request.user.is_authenticated:
        if request.method == 'POST':
            form = CreateNewList(request.POST)

            if form.is_valid():
                name = form.cleaned_data["name"]
                s_balance = form.cleaned_data["starting_balance"]
                t_list = TransactionList(name=name, starting_balance=s_balance)
                t_list.save()
                request.user.transactionlist.add(t_list)

                date = timezone.now()
                payee = "Starting Balance"
                ingoing = form.cleaned_data["starting_balance"]

                s_transaction = Transaction(t_list=t_list,
                                            date_posted=date,
                                            payee=payee,
                                            memo="",
                                            ingoing=ingoing,
                                            outgoing=0.00,
                                            )
                s_transaction.save()

                return redirect("/dashboard/%i" % t_list.id + "?id=%i" % t_list.id)
        else:
            form = CreateNewList()

        return render(request, "budgeter/create.html", {"form": form, "title": "Create a New Budget"})

    return render(request, "budgeter/error.html", {'title': '404 Error'})


def dashboard(request, id):
    """Dashboard-view renders the dashboard template with
    the User's chosen TransactionList. The view renders a form
    for the User to enter and save new Transactions into their
    TransactionList.

    If the User is not logged-in, then the view renders a custom 404
    Error page.

    Variables passed through to the template:
        title: :class:`String`
            Title of the view.
        form: :class:`form`
            Rendered Transaction form for the User.
        transactions: :class:`Model Transaction`
            Transactions of the TransactionList to be rendered in
            the template.
        t_list: :class:`Model TransactionList`
            TransactionList that contains Transactions to be rendered
            in the template.
        ingoing_sum: :class:`Float`
            Sum of all the ingoing values across every Transaction.
        outgoing_sum: :class:`Float`
            Sum of all the outgoing values across every Transaction.
        total_bal: :class:`Float`
            The current, total balance by subtracting the ingoing_sum
            and the out_going sum.
    """

    t_list = TransactionList.objects.get(id=id)

    if t_list in request.user.transactionlist.all():
        if request.method == 'POST':
            form = CreateNewTransaction(request.POST)

            if form.is_valid():
                date = form.cleaned_data["date_posted"]
                payee = form.cleaned_data["payee"]
                memo = form.cleaned_data["memo"]
                ingoing = form.cleaned_data["ingoing"]
                outgoing = form.cleaned_data["outgoing"]

                transaction = Transaction(t_list=t_list,
                                          date_posted=date,
                                          payee=payee,
                                          memo=memo,
                                          ingoing=ingoing,
                                          outgoing=outgoing
                                          )
                transaction.save()

                return redirect("/dashboard/%i" % t_list.id + "?id=%i" % t_list.id)
        else:
            form = CreateNewTransaction()

        context = {'title': 'My Dashboard',
                   'form': form,
                   'transactions': t_list.transaction.all().order_by('-date_posted'),
                   't_list': t_list
                   }

        # Aggregate values from Transactions
        if t_list.transaction.exists():
            ingoing_sum: float = t_list.transaction.all().aggregate(in_sum=Sum('ingoing'))['in_sum']
            outgoing_sum: float = t_list.transaction.all().aggregate(out_sum=Sum('outgoing'))['out_sum']
            total_bal: float = ingoing_sum - outgoing_sum

            context['ingoing_sum'] = ingoing_sum
            context['outgoing_sum'] = outgoing_sum
            context['total_bal'] = total_bal

        return render(request, 'budgeter/dashboard.html', context)

    return render(request, 'budgeter/error.html', {'title': '404 Error'})


class TransactionListListView(LoginRequiredMixin, ListView):
    """ListView for all of the TransactionLists. Allows the User
    to see all of their created budgets so that they may pick
    which one to edit.

    Currently a work in progress.
    """

    model = TransactionList
    template_name = 'budgeter/budget_list.html'
    context_object_name = 'transaction_lists'
    ordering = ['name']

    def get_queryset(self):
        return TransactionList.objects.filter(user=self.request.user)


class TransactionDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """DeleteView for all the Transactions. Allows the User
    to delete Transactions from their TransactionLists.
    """

    model = Transaction
    success_url = '/'

    def test_func(self):
        return True

budgeter/templates/budgeter/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="author" content="Kevin L." />
    <meta
      name="description"
      content="Budgeter: A Financial Tracker Developed in Python with Django Web Framework and Bootstrap4."
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <!-- Google Fonts -->
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap");
    </style>

    <!-- Local CSS -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'budgeter/main.css' %}"
    />

    <!-- Title -->
    {% if title %}
    <title>Budgeter - {{ title }}</title>
    {% else %}
    <title>Budgeter</title>
    {% endif %}

  </head>
  <body>

    <!-- NavBar -->
    <nav
      role="navigation"
      class="navbar navbar-expend-md justify-content-center budgeter-nav"
      id="mainNav"
    >
      <div class="container-fluid">
        <a href="{% url 'budgeter-home' %}" class="navbar-brand budgeter-logo">
          &#128184; Budgeter
        </a>
        <div
          class="navbar flex-grow-2 text-right"
          id="navbarResponsive"
        >
          {% if user.is_authenticated %}
            <a href="{% url 'budgeter-home' %}" class="navbar-link mr-3">Dashboard</a>
            <a href="{% url 'logout-page' %}" class="navbar-link">Logout</a>
          {% else %}
            <a href="{% url 'login-page' %}" class="navbar-link mr-3">Login</a>
            <a href="{% url 'register-page' %}" class="navbar-link">Register</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <!-- End NavBar -->

    <!-- Main -->
    <main class="budgeter-main">
      <div class="pt-3">
        {% if messages %} {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %} {% endif %}
      </div>

      {% block content %} {% endblock content %}

    </main>
    <!-- End Main -->

    <!-- Footer -->
    <footer>
      Copyright &copy; 2021 Kevin L. All rights reserved.
    </footer>

  </body>
</html>

budgeter/templates/budgeter/budget_list.html
{% extends "budgeter/base.html" %}
{% block content %}
    <div class="container-fluid">
      <div class="border-bottom pt-3">
        <h2>Budget List</h2>
      </div>
      <br />
    {% for transaction_list in transaction_lists %}
      <a class="btn btn-outline-info budget text-right mb-3"
         href="{% url 'budgeter-dashboard' transaction_list.id %}"
      >{{ transaction_list.name }}</a
      >
      <br />
    {% endfor %}
    </div>
{% endblock content %}

budgeter/templates/budgeter/create.html
{% extends "budgeter/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <form method="post" action="/create/" class="form-group">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom pt-3 mb-4">Create a New Budget</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Create Budget</button>
    </div>
  </form>
</div>
{% endblock content %}

budgeter/templates/budgeter/dashboard.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="author" content="Kevin L." />
    <meta
      name="description"
      content="Budgeter: A Financial Tracker Developed in Python with Django Web Framework and Bootstrap4."
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <!-- jQuery CSS -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- JavaScript -->
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- Date-picker -->
    <script>
    $( function() {
      $( ".datepicker" ).datepicker();
    } );
    </script>

    <!-- Google Fonts -->
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap");
    </style>

    <!-- Local CSS -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'budgeter/main.css' %}"
    />

    <!-- Title -->
    {% if title %}
    <title>Budgeter - {{ title }}</title>
    {% else %}
    <title>Budgeter</title>
    {% endif %}

  </head>
  <body>

    <!-- NavBar -->
    <nav
      role="navigation"
      class="navbar navbar-expend-md justify-content-center budgeter-nav"
      id="mainNav"
    >
      <div class="container-fluid">
        <a href="{% url 'budgeter-home' %}" class="navbar-brand budgeter-logo">
          &#128184; Budgeter
        </a>
        <div
          class="navbar flex-grow-2 text-right"
          id="navbarResponsive"
        >
          {% if user.is_authenticated %}
            <a href="{% url 'budgeter-home' %}" class="navbar-link">Dashboard</a>
            <a href="{% url 'logout-page' %}" class="navbar-link">Logout</a>
          {% else %}
            <a href="{% url 'login-page' %}" class="navbar-link mr-3">Login</a>
            <a href="{% url 'register-page' %}" class="navbar-link">Register</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <!-- End NavBar -->

    <main class="main">
      <!-- Budget Buttons -->
      <div class="container-fluid mt-3 text-left">
        <a href="{% url 'transactionlist-lists' %}" class="btn btn-outline-info mr-2">My Budgets</a>
        <a href="{% url 'budgeter-create' %}" class="btn btn-outline-info">Create a New Budget</a>
      </div>
      <!-- End Budget Buttons -->

      <br />

      <!-- Title of Budget -->
      <div class="container-fluid mt-3">
        <h1>{{ t_list.name }}</h1>
      </div>
      <!-- Title of Budget -->

      <!-- New-transaction Form -->
      <form method="post" action="#">
        <div class="container-fluid">
          {% csrf_token %}
          <fieldset class="form-row">
          <legend class="new-transaction border-bottom pt-3 mb-4">New Transaction</legend>
            {{ form|crispy }}
          </fieldset>
          <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Save Transaction</button>
          </div>
        </div>
      </form>
      <!-- End New-transaction Form -->

      <br />

      <!-- Table of Transactions -->
      <div class="container-fluid">
        <table class="table table-striped table-bordered table-hover">
          <thead class="thead-light">
            <tr>
              <th scope="col" colspan="3" class="text-left">
                  {% if total_bal >= 0 %}
                      <strong class="transaction-table-header">Current Balance: <span class="positive">${{ total_bal|floatformat:2 }}</span></strong>
                  {% else %}
                      <strong class="transaction-table-header">Current Balance: <span class="negative">${{ total_bal|floatformat:2 }}</span></strong>
                  {% endif %}
              </th>
              <th scope="col">
                  <strong class="transaction-table-header">In-going:</strong>
              </th>
              <th scope="col">
                  <strong class="transaction-table-header">Out-going:</strong>
              </th>
              <th scope="col"></th>
            </tr>
          </thead>
          <thead class="thead-light">
            <tr>
              <th scope="col"><strong>Date</strong></th>
              <th scope="col"><strong>Payee</strong></th>
              <th scope="col"><strong>Memo</strong></th>
              <th scope="col" colspan="1">
                  <strong>${{ ingoing_sum|floatformat:2 }}</strong>
              </th>
              <th scope="col" colspan="1">
                  <strong>${{ outgoing_sum|floatformat:2 }}</strong>
              </th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody class="">
          {% for transaction in transactions %}
            <tr>
              <th scope="row" style="width: 10%">{{ transaction.date_posted }}</th>
              <td style="width: 17.5%">{{ transaction.payee }}</td>
              <td style="width: 51.5%">{{ transaction.memo }}</td>
              <td style="width: 10%">${{ transaction.ingoing }}</td>
              <td style="width: 10%">${{ transaction.outgoing }}</td>
              <td style="width: 1%" class="text-right">
                <!-- Delete Button -->
                <a class="btn btn-outline-danger btn-sm text-right" href="{% url 'transaction-delete' transaction.id %}">
                  <!-- Trash Icon for Delete Button -->
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                  </svg>
                </a>
                <!-- End Delete Button -->
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <!-- End Table of Transactions -->

    </main>
    <!-- End Main -->

    <!-- Footer -->
    <footer>
      Copyright &copy; 2021 Kevin L. All rights reserved.
    </footer>

  </body>
</html>

budgeter/templates/budgeter/error.html
{% extends "budgeter/base.html" %}
{% block content %}
    <div class="container-fluid">
      <div class="border-bottom pt-3">
        <h2>Page not found.</h2>
      </div>
      <br />
      <small class="text-muted">
        <a href="{% url 'budgeter-home' %}" class="ml-2">Head back home.</a>
      </small>
    </div>
{% endblock content %}

budgeter/templates/budgeter/home.html
{% extends "budgeter/base.html" %}
{% load static %}
{% block content %}
    <h1 class="fade-in mt-3">Welcome to Budgeter.</h1>
    <div class="home-layout">
      <div class="box fade-in">
        <div class="content">
          <img src="{% static 'budgeter/home-page/money1.jpg' %}" alt="" />
          <p>
            Around <span class="emphasize-text">25%</span> of all American families have no savings at all, while around <span class="emphasize-text">40%</span> of all working Americans are not saving any money for retirement.
            <br />
            <br />
            <strong>Budgeter</strong> can help you begin saving money and plan for your retirement.
          </p>
        </div>
      </div>
      <div class="box fade-in">
        <div class="content">
          <img src="{% static 'budgeter/home-page/money2.jpg' %}" alt="" />
          <p>
            Keep track of all of your transactions: ingoing and outgoing.
            <br />
            <br />
              Being able to see where your money is <strong>going</strong> will provide you with insight on your <span class="emphasize-text">spending habits</span>.
          </p>
        </div>
      </div>
      <div class="box fade-in">
        <div class="content">
          <img src="{% static 'budgeter/home-page/mental-money.webp' %}" alt="" />
          <p>
            Money and mental health are connected <strong>very closely</strong>.
            <br />
            Saving and budgeting your money will result in less financial worry and leave you in a <span class="emphasize-text">healthier</span> mental state.
          </p>
        </div>
      </div>
      <div class="box fade-in">
        <div class="content">
          <img src="{% static 'budgeter/home-page/money3.webp' %}" alt="" />
          <p>
              Saving money allows you to <span class="emphasize-text">comfortably</span> make bigger purchases down the line.
          </p>
        </div>
      </div>
      <a href="{% url 'register-page' %}" class="box home-link fade-in">
        <div class="">
           Start Saving Today
        </div>
      </a>

    </div>
{% endblock content %}

budgeter/templates/budgeter/transaction_confirm_delete.html
{% extends "budgeter/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container-fluid">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <h2 class="border-bottom mb-4">Delete Transaction</h2>
          <h4>Are you sure you want to delete the transaction:
            <div class="container-fluid mt-4">
              <table class="table table-striped table-bordered table-hover">
                <thead class="thead-light">
                  <tr>
                    <th scope="col"><strong>Date</strong></th>
                    <th scope="col"><strong>Payee</strong></th>
                    <th scope="col"><strong>Memo</strong></th>
                    <th scope="col"><strong>Ingoing</strong></th>
                    <th scope="col"><strong>Outgoing</strong></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row" style="width: 10%">{{ object.date_posted }}</th>
                    <td style="width: 17.5%">{{ object.payee }}</td>
                    <td style="width: 51.5%">{{ object.memo }}</td>
                    <td style="width: 10%">${{ object.ingoing }}</td>
                    <td style="width: 10%">${{ object.outgoing }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </h4>
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-danger" type="submit">Delete</button>
          <a class="btn btn-outline-secondary" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
        </div>
      </form>
    </div>
{% endblock content %}